PKTasks.Web/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TasksBL;
using TasksDB;

namespace PKTasks.Web.Controllers
{
    public class NotesController : Controller
    {
        // GET: Notes
        public ActionResult Index()
        {
            return View();
        }



        public ActionResult NoteAddView(int humanId, int entryId, Enumerations.PKTasksEntryType entryType)
        {
            Models.NoteVM noteVM = new Models.NoteVM(humanId, entryId, entryType);
            return View(noteVM);
        }


        public ActionResult NoteAdd(Models.NoteVM noteVM)
        {
            NotesService srvnt = new NotesService();
            HumanResourceService srvhr = new HumanResourceService();
            HumanResource human = srvhr.ReturnOneHumanResource(Globals.UserId);
            Note note = new Note();
            note.EntryId = noteVM.EntryId;
            note.EntryTypeId = (byte)noteVM.EntryType;
            note.HumanResourceId = human.Id;
            note.Message = noteVM.Message;
            note.PostDate = DateTime.Now;
            srvnt.Add(note);
            return Json(true);
        }


        public ActionResult EntryNotesView(int EntryId, byte EntryTypeId)
        {
            NotesService srvnt = new NotesService();
            List<Note> notes = srvnt.GetAllNotes(EntryId, EntryTypeId);

            Models.NotesVM notesVM = new Models.NotesVM(notes);
            return View(notesVM);
        }


        public ActionResult FullNoteView(int noteId)
        {
            NotesService srvnt = new NotesService();
            Note note = srvnt.ReturnOneNotebyId(noteId);
            Models.NoteVM noteVM = new Models.NoteVM(note);
            return View(noteVM);
        }

    }
}

PKTasks.Web/Views/Notes/EntryNotesView.cshtml
@model PKTasks.Web.Models.NotesVM
@{
    Layout = null;
}

<div style="overflow-y:auto; height:400px; background-color:antiquewhite; width:60%">

    <table style="width:100%">
        <tr>
            <th><h3>Ημερομηνία</h3></th>
            <th><h3>Συγγραφέας</h3></th>
            <th ><h3>Μήνυμα</h3></th>
           
        </tr>
        @foreach (var item in Model.Notes)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PostDate)</td>
                <td>@Html.DisplayFor(modelItem => item.HumanResourceName)</td>
               
                    <td><div class="submessage">@Html.DisplayFor(modelItem => item.Message)</div></td>
                
                <td><a class="fullMessageLink" data-id="@item.Id">Προβολή</a></td>

            </tr>
        }
    </table>
</div>




    @Scripts.Render("~/plugins/datePicker")

    <script type="text/javascript">

        $('.fullMessageLink').click(function () {
            ProteasJS.showModalWindow({
                actionUrl: '/Notes/FullNoteView?noteId=' + $(this).data('id'),
                size: 'lg',
                title: 'Σημείωση'
                });
                });

    </script>

PKTasks.Web/Views/Notes/FullNoteView.cshtml
@model PKTasks.Web.Models.NoteVM
@{
    Layout = null;
}

<div style="overflow-y:auto; height:400px; background-color:antiquewhite; width:100%">

    <table style="width:100%">
        <tr>
            <th class="width120px"><h3>Ημερομηνία</h3></th>
            
            <td>@Model.PostDate.ToString("dd/MM/yyyy HH:mm:ss")</td>
        </tr>
        <tr>
            <th><h3>Συγγραφέας</h3></th>
            
            <td>@Html.DisplayFor(modelItem => Model.HumanResourceName)</td>
        </tr>
        <tr>
            <th><h3>Μήνυμα</h3></th>
            
            <td>@Html.DisplayFor(modelItem => Model.Message)</td>
        </tr>

    </table>
</div>


PKTasks.Web/Views/Notes/NoteAddView.cshtml
@model PKTasks.Web.Models.NoteVM
@{
    Layout = null;
}


@using (Ajax.BeginForm("NoteAdd", "Notes", null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "onNoteAdded" }, new { enctype = "multipart/form-data", id = "frmAddAddress", @class = "form-horizontal" }))
{
    @Html.HiddenFor(modelItem => modelItem.HumanResourceId)
    @Html.HiddenFor(modelItem => modelItem.EntryId)
    @Html.HiddenFor(modelItem => modelItem.EntryType)
    <div>
        <table>
            <tr>

                <td>@Html.DisplayNameFor(modelItem => modelItem.Message)</td>
                @*<td>@Html.DisplayNameFor(modelItem => modelItem.HumanResourceName)</td>*@
            </tr>
            <tr>

                <td>@Html.EditorFor(modelItem => modelItem.Message)</td>
                @*<td>@Html.EditorFor(modelItem => modelItem.HumanResourceName)</td>*@
            </tr>
        </table>
        <button type="submit">OK</button>
        <button type="reset">Άκυρο</button>
    </div>

}

<script type="text/javascript">
    function onNoteAdded(response) {
        if (response == true) {
            ProteasJS.hideModalWindow();
            RefreshNotes();
        }
        else {
            alert("failure");
        }
    }
</script>